"""Decision strategy interfaces for agent-based modeling.

This module implements the Strategy Pattern to decouple agent embodiment
from decision-making logic, enabling comparison between algorithmic and
LLM-based agent behaviors.
"""

from abc import ABC, abstractmethod
from typing import Any


class DecisionStrategy(ABC):
    """Abstract base class for agent decision-making strategies.

    This interface defines the contract for all decision strategies,
    whether algorithmic (rule-based) or LLM-driven (prompt-based).
    """

    @abstractmethod
    def decide(self, context: dict[str, Any]) -> dict[str, Any]:
        """Make a decision based on the provided context.

        Args:
            context: Environmental and agent state information needed
                for decision-making. Structure varies by simulation type.

        Returns:
            A dictionary containing the decided action(s) and any
            associated parameters.
        """
        pass


class HeuristicStrategy(DecisionStrategy):
    """Algorithmic strategy using hard-coded rules and heuristics.

    This strategy implements traditional rule-based decision-making
    with explicit if-then logic. Serves as the baseline for comparison
    against LLM-based approaches.
    """

    def decide(self, context: dict[str, Any]) -> dict[str, Any]:
        """Make decisions using algorithmic rules.

        Args:
            context: Environmental and agent state information.

        Returns:
            Action dictionary determined by hard-coded logic.
        """
        return {"action": "idle"}


class LLMStrategy(DecisionStrategy):
    """LLM-driven strategy using prompt-based decision-making.

    This strategy leverages Large Language Models to generate agent
    behaviors through natural language processing, receiving environmental
    data as context and producing actions through prompt engineering.
    """

    def __init__(self, client: Any) -> None:
        """Initialize LLM strategy with a configured client.

        Args:
            client: LLM client configured with instructor for structured outputs.
        """
        self.client = client

    def decide(self, context: dict[str, Any]) -> dict[str, Any]:
        """Make decisions using LLM inference.

        Args:
            context: Environmental and agent state information formatted
                for LLM prompt construction.

        Returns:
            Action dictionary generated by LLM response parsing.
        """
        return {"action": "idle"}
